name: Build App

on:
  push:
    branches:
    - main

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - uses: sburris/dependency-check-action@master
      with:
        Project-Name: TestApp
    - name: Archive dependency check reports
      uses: actions/upload-artifact@v1
      with:
        name: reports
        path: reports
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        repository: 3r1co/cd
        tag_with_sha: true
    - name: use klar
      run: |
        wget https://github.com/optiopay/klar/releases/download/v2.4.0/klar-2.4.0-linux-amd64 -O klar
        chmod +x klar
        CLAIR_ADDR=http://clair.3r1.co:6060 ./klar docker.io/3r1co/cd:$(git rev-parse --short HEAD)%
