name: Build App

on:
  push:
    branches:
    - main

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    #- uses: sburris/dependency-check-action@master
    #  with:
    #    Project-Name: TestApp
    #- name: Archive dependency check reports
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: reports
    #    path: reports
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.io
        repository: 3r1co/cd
        #tag_with_sha: true
        #tag_with_ref: true
        tags: latest
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: docker.io/3r1co/cd:latest
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
